### ISSUE TITLE
Autoloading does not seem to work when extending classes

### ISSUE THREAD

**Issue by grandeljay** [RobinTheHood/modified-composer-autoload#3]
When you define a class that has to be autoloaded and extend it with another class that needs to be autoloaded, the extending class will not be found.

Example:
```php
class vendor_modulename extends StdModule
```

will work, but 
```php
class MyClass extends MyOtherClass
```

will not work.

**Comment by grandeljay** [comment]
Never mind, sorry. I found a typo 🤦🏼‍♂️

**Comment by RobinTheHood** [comment]
No problem, it happens to the best of us. Thanks anyway for using Issus.
